name: Deploy to EC2

on:
  push:
    branches: 
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PROJECT_DIR }}
            git pull ${{ secrets.GIT_REPO_URL }} main
            NODE_OPTIONS="--max-old-space-size=4096" ${{ secrets.NODE_PATH }} install --production
            NODE_OPTIONS="--max-old-space-size=4096" ${{ secrets.NODE_PATH }} run build
            ${{ secrets.PM2_PATH }} restart ${{ secrets.PM2_SERVICE }}
